#!/usr/bin/env bash
[[ " help auto-deploy:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/help-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-auto-deploy-help "$@"
